version: '3.8'

services:
  main:
    container_name: dropengine_main
    image: dropengine-api:1.0.1
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - ${WEBSITES_PORT}:${WEBSITES_PORT}
      - 9228:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    command: yarn start:debug
    env_file:
      - .env
    depends_on:
      - db
      - mongo
    networks:
      - webnet
    environment:
      # DEBUG: "*"
      NODE_ENV: "development"
  db:
    container_name: dropengine_psql
    hostname: psql
    build:
      context: ./docker/postgres
      target: build
      dockerfile: Dockerfile
    working_dir: /usr/src/db
    ports:
      - '6544:5432'
    expose:
      - '5432'
    volumes:
      # - ./seed.db.sql:/docker-entrypoint-initdb.d/db.sql
      - pgdata:/var/lib/postgresql/data # or specify a local folder like 
      # - ./.volumes/pgdata:/var/lib/postgresql/data
      # - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - webnet
  # db:
  #   image: postgres:13
  #   container_name: dropengine_psql
  #   hostname: psql
  #   restart: always
  #   ports:
  #     - '6544:5432'
  #   expose:
  #     - '5432'
  #   env_file:
  #     - .env
  #   volumes:
  #     # - ./seed.db.sql:/docker-entrypoint-initdb.d/db.sql
  #     # - ./.volumes/pgdata:/var/lib/postgresql/data
  #     - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - postgres:/var/lib/postgresql/data
  #   networks:
  #     - webnet
  mongo:
    image: mongo:5.0
    container_name: dropengine_mongo
    hostname: mongo
    ports:
      - '6545:27017'
    expose:
      - '27017'
    volumes:
      - mongo:/data/db
    networks:
      - webnet
volumes:
  pgdata:
    name: pgdata
  mongo:
    name: mongo_volume
networks:
  webnet:
    name: webnet
