version: '3.8'

services:
  e2e-test-runner:
    container_name: dropengine_main_e2e
    image: dropengine-api-e2e:1.0.1
    build:
      context: .
      target: build
      dockerfile: Dockerfile.e2e
    working_dir: /usr/src/app
    ports:
      - ${WEBSITES_PORT}:${WEBSITES_PORT}
      - 9228:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./results/:/usr/src/app/e2e/results
    restart: always
    command: yarn test:e2e
    env_file:
      - ./e2e.docker.env
    depends_on:
      - db
      - mongo
    networks:
      - webnet_e2e
    environment:
      # DEBUG: "*"
      NODE_ENV: "development"
  db:
    container_name: dropengine_psql_e2e
    hostname: psql
    build:
      context: ./docker/postgres
      target: build
      dockerfile: Dockerfile
    working_dir: /usr/src/db
    ports:
      - '6544:5432'
    expose:
      - '5432'
    volumes:
      # - ./seed.db.sql:/docker-entrypoint-initdb.d/db.sql
      - pgdata:/var/lib/postgresql/data # or specify a local folder like 
      # - ./.volumes/pgdata:/var/lib/postgresql/data
      # - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    env_file:
      - ./e2e.docker.env
    networks:
      - webnet_e2e
  # db:
  #   image: postgres:13
  #   container_name: dropengine_psql_e2e
  #   hostname: psql
  #   restart: always
  #   ports:
  #     - '6544:5432'
  #   expose:
  #     - '5432'
  #   env_file:
  #     - ./e2e.docker.env
  #   volumes:
  #     # - ./seed.db.sql:/docker-entrypoint-initdb.d/db.sql
  #     - pgdata:/var/lib/postgresql/data # or specify a local folder like 
  #     # - ./.volumes/pgdata:/var/lib/postgresql/data
  #     - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   networks:
  #     - webnet_e2e
  mongo:
    image: mongo:5.0
    container_name: dropengine_mongo_e2e
    hostname: mongo
    ports:
      - '6545:27017'
    expose:
      - '27017'
    volumes:
      - mongodata:/data/db
    networks:
      - webnet_e2e
volumes:
  pgdata:
    name: postgres_volume_e2e
  mongodata:
    name: mongo_volume_e2e
networks:
  webnet_e2e:
    name: webnet_e2e
