version: '3.8'

services:
  e2e:
    container_name: dropengine-api-e2e
    image: dropengine-api-e2e:1.0.1
    build:
      context: .
      target: build
      dockerfile: Dockerfile.e2e
    working_dir: /usr/src/app
    ports:
      - ${WEBSITES_PORT}:${WEBSITES_PORT}
      - 9228:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./results/:/usr/src/app/e2e/results
    restart: always
    command: yarn test:e2e
    env_file:
      - ./e2e.docker.env
    depends_on:
      - db
      - mongo
    networks:
      - webnet-e2e
    environment:
      # DEBUG: "*"
      NODE_ENV: "development"
  db:
    container_name: dropengine-psql-e2e
    hostname: psql
    build:
      context: ./docker/postgres
      target: build
      dockerfile: Dockerfile
    working_dir: /usr/src/db
    ports:
      - '6544:5432'
    expose:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data 
    restart: always
    env_file:
      - ./e2e.docker.env
    networks:
      - webnet-e2e
  mongo:
    image: mongo:5.0
    container_name: dropengine-mongo-e2e
    hostname: mongo
    ports:
      - '6545:27017'
    expose:
      - '27017'
    volumes:
      - mongo:/data/db
    networks:
      - webnet-e2e
volumes:
  pgdata:
    name: pgdata
  mongo:
    name: mongodata
networks:
  webnet-e2e:
    name: webnet-e2e
