version: '3.8'

services:
  main:
    container_name: dropengine-api
    image: dropengine-api:1.0.1
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - ${WEBSITES_PORT}:${WEBSITES_PORT}
      - 9228:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    command: yarn start:debug
    env_file:
      - .env
    depends_on:
      - db
      - mongo
    networks:
      - webnet
    environment:
      # DEBUG: "*"
      NODE_ENV: "development"
  db:
    container_name: dropengine-psql
    hostname: psql
    build:
      context: ./docker/postgres
      target: build
      dockerfile: Dockerfile
    working_dir: /usr/src/db
    ports:
      - '6544:5432'
    expose:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data 
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - webnet
  mongo:
    image: mongo:5.0
    container_name: dropengine-mongo
    hostname: mongo
    ports:
      - '6545:27017'
    expose:
      - '27017'
    volumes:
      - mongo:/data/db
    networks:
      - webnet
volumes:
  pgdata:
    name: pgdata
  mongo:
    name: mongodata
networks:
  webnet:
    name: webnet
