formats:
  - oas3.1
extends:
  - 'spectral:oas'
rules:
  info-matches-dropengine:
    description: This is an example rule for DropEngine
    message: Info must contain summary
    given: $.info
    recommended: true
    type: style
    then:
      field: title
      function: truthy
